- 👋 Hi, I’m @uuwushh
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
uuwushh/uuwushh is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
its ford bajaj 12.37355ltv 33% 34000 done by bajaj office 
